version: "3.3"

services:
  client:
    image: tcodemalans/qrscanner-client:latest
    networks:
      - scannernet
    ports:
      - 80:5000

  server:
    image: tcodemalans/qrscanner-server:latest
    depends_on:
      - db
    networks:
      - scannernet
    environment:
      - JDBC_URI
      - MYSQL_PASSWORD
      - SERVER_TESTMODE
    ports:
      - 7778:7778

  db:
    image: mysql:8.0
    #ports:
     # - 3306:3306
    networks:
      - scannernet
    # Variables values have to be set from outside, e.g. via .env file
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_DATABASE
    command: --skip-name-resolve=false
    volumes:
      - ./db-data/v1:/docker-entrypoint-initdb.d

networks:
  scannernet:
    driver: bridge